// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiSumulatorDb;

#nullable disable

namespace TaxiSimulatorDb.Migrations
{
    [DbContext(typeof(TaxiSumulatorDbContext))]
    partial class TaxiSumulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TaxiSumulatorDb.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeparturePoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPoint")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DriveStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Plan")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Price")
                        .HasColumnType("REAL");

                    b.Property<long?>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WaitingStartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
